force-app/main/default/objects/ContractHistory__c/ContractHistory__c.object-meta.xml
<CustomObject>
    <label>契約履歴</label>
    <pluralLabel>契約履歴</pluralLabel>
    <nameField>
        <label>契約履歴名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractHistory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>タイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Renew</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractService__c/ContractService__c.object-meta.xml
<CustomObject>
    <label>契約サービス</label>
    <nameField>
        <label>契約サービス名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>契約サービス</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContractHistoryVersionUtilTest.cls
@IsTest
private class ContractHistoryVersionUtilTest {
    @TestSetup
    static void setupAccess() {
        ContractTestDataFactory.initTestContext();
    }

    @IsTest

    static void getNextHistoryVersion_returnsOneForNewService() {

        System.runAs(ContractTestDataFactory.getAdminUser()) {

            Account account = ContractTestDataFactory.insertAccount('Version Account');



            ContractService__c service = new ContractService__c(

                Name = 'Version Service',

                Account__c = account.Id

            );

            insert service;



            System.assertEquals(

                1,

                ContractHistoryVersionUtil.getNextHistoryVersion(service.Id)

            );

        }

    }



    @IsTest

    static void allocateNextVersion_incrementsWithinBatch() {

        System.runAs(ContractTestDataFactory.getAdminUser()) {

            Account account = ContractTestDataFactory.insertAccount('Batch Version Account');



            ContractService__c service = new ContractService__c(

                Name = 'Batch Version Service',

                Account__c = account.Id

            );

            insert service;



            insert new ContractHistory__c(

                Name = 'History v1',

                ContractService__c = service.Id,

                Type__c = 'New',

                historystatus__c = 'Estimate',

                Version__c = 1

            );



            Map<Id, Decimal> allocator = ContractHistoryVersionUtil.buildVersionAllocator(

                new Set<Id>{ service.Id }

            );



            System.assertEquals(

                2,

                ContractHistoryVersionUtil.allocateNextVersion(allocator, service.Id)

            );

            System.assertEquals(

                3,

                ContractHistoryVersionUtil.allocateNextVersion(allocator, service.Id)

            );

        }

    }

}